services:
  db:
    image: postgres:14.4
    environment:
      POSTGRES_PASSWORD: "strong-password"
    ports:
      - 5432:5432

  jaeger:
    image: jaegertracing/all-in-one:1.18
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686 # web
      - 14268:14268
      - 9411:9411

  memcached:
    image: memcached:latest
    ports:
      - "11211:11211"
